binary_sensor:
  # Garage Motion Sensor from HA #  
  - platform: homeassistant
    id: id_ha_motion_garage
    entity_id: binary_sensor.presence_dans_le_garage
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_motion_status
            text_color: color_red
    on_release:
      then:
      - lvgl.label.update: 
          id: id_lv_lab_motion_status
          text_color: color_dark_gray

  # Garage SS Motion Sensor from HA #
  - platform: homeassistant
    id: id_ha_motion_garage_ss
    entity_id: binary_sensor.presence_dans_le_sous_sol_garage
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_motion_ss_status
            text_color: color_red
    on_release:
      then:
      - lvgl.label.update: 
          id: id_lv_lab_motion_ss_status
          text_color: color_dark_gray

  # Garage inside door to basement from HA #
  - platform: homeassistant
    id: id_ha_indoor_basement
    entity_id: binary_sensor.ademcointerposer_interieur_garage_ss
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_basement_door_status
            text_color: color_green
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_basement_door_status
            text_color: color_dark_gray

  # Garage inside door to ground floor from HA #
  - platform: homeassistant
    id: id_ha_indoor_rdc
    entity_id: binary_sensor.ademcointerposer_interieur_garage_rdc
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_groundfloor_door_status
            text_color: color_green
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_groundfloor_door_status
            text_color: color_dark_gray
  
  # Whole Home Lights #
  - platform: homeassistant
    id: id_bin_all_light_state
    internal: True
    entity_id: light.toutes_les_lumieres_sauf_eclairage_exterieur
    publish_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_widget_but_all
            hidden: False
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_widget_but_all
            hidden: True

sensor:
  # Weather temperature
  - platform: homeassistant
    id: weather_temp
    entity_id: weather.maison
    attribute: temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: id_lv_lab_weather_temperature
            text:
              format: "%.1f°C"
              args: x
              
  # Weather humidity
  - platform: homeassistant
    id: weather_hum
    entity_id: weather.maison
    attribute: humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: id_lv_lab_weather_humidity
            text:
              format: "%.0f%%"
              args: x
  # Weather wind speed
  - platform: homeassistant
    id: weather_precipitation
    entity_id: weather.maison
    attribute: wind_speed
    on_value: 
      then:
        - lvgl.label.update:
            id: id_lv_lab_weather_wind_speed
            text:
              format: "%.0fkm/h"
              args: x

  - platform: homeassistant
    id: gr_temp
    internal: True
    entity_id: sensor.yaris_remote_temperature
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_temperature_garage_rdc
            text:
              format: "%.1f°C"
              args: x
  - platform: homeassistant
    id: gr_hum
    internal: True
    entity_id: sensor.yaris_remote_humidty
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_humidity_garage_rdc
            text:
              format: "%.0f%%"
              args: x
  - platform: homeassistant
    id: gs_temp
    internal: True
    entity_id: sensor.acurite_tower_c_241_temperature
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_temperature_garage_ss
            text:
              format: "%.1f°C"
              args: x
  - platform: homeassistant
    id: gs_hum
    internal: True
    entity_id: sensor.acurite_tower_c_241_humidity
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_humidity_garage_ss
            text:
              format: "%.0f%%"
              args: x

text_sensor:
  # Sun horizon sensor from Home Assistant #
  - platform: homeassistant
    id: sun_state
    entity_id: sun.sun

  # Weather state from Home Assistant #
  - platform: homeassistant
    id: weather_state
    entity_id: weather.maison
    on_value: 
      then:
        - lambda: |-
            if (id(sun_state).state == "below_horizon" && (id(weather_state).state == "cloudy" || id(weather_state).state == "partlycloudy")) {
            lv_obj_clear_flag(id(weather_partlycloudy_moon), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_partlycloudy_moon), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(sun_state).state != "below_horizon" && id(weather_state).state == "cloudy") {
            lv_obj_clear_flag(id(weather_cloudy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_cloudy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(sun_state).state != "below_horizon" && id(weather_state).state == "partlycloudy") {
            lv_obj_clear_flag(id(weather_partlycloudy_sun), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_partlycloudy_sun), LV_OBJ_FLAG_HIDDEN);
            }
            if ((id(sun_state).state != "below_horizon" && id(weather_state).state == "sunny") || (id(sun_state).state != "below_horizon" && id(weather_state).state == "clear-night")) {
            lv_obj_clear_flag(id(weather_sunny), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_sunny), LV_OBJ_FLAG_HIDDEN);
            }
            if ((id(sun_state).state == "below_horizon" && id(weather_state).state == "sunny") || (id(sun_state).state == "below_horizon" && id(weather_state).state == "clear-night")) {
            lv_obj_clear_flag(id(weather_clear_night), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_clear_night), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "rainy") {
            lv_obj_clear_flag(id(weather_rainy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_rainy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "lightning-rainy") {
            lv_obj_clear_flag(id(weather_lightning_rainy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_lightning_rainy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "lightning") {
            lv_obj_clear_flag(id(weather_lightning), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_lightning), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "pouring") {
            lv_obj_clear_flag(id(weather_pouring), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_pouring), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "snowy") {
            lv_obj_clear_flag(id(weather_snowy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_snowy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "snowy-rainy") {
            lv_obj_clear_flag(id(weather_snowy_rainy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_snowy_rainy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "fog") {
            lv_obj_clear_flag(id(weather_fog), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_fog), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "hail") {
            lv_obj_clear_flag(id(weather_hail), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_hail), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "windy") {
            lv_obj_clear_flag(id(weather_windy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_windy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_state).state == "windy-variant") {
            lv_obj_clear_flag(id(weather_windy_variant), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_windy_variant), LV_OBJ_FLAG_HIDDEN);
            }
  
lvgl:
  pages:
    - id: page_home
      skip: True
      bg_color: color_black
      scrollable: False
      widgets:
        - <<: !include datetime_widget.yaml
        - <<: !include weather_widget.yaml
        - <<: !include main_tileview.yaml
        - obj:
                  id: id_widget_but_all
                  bg_opa: TRANSP
                  border_opa: TRANSP
                  shadow_opa: TRANSP
                  pad_all: 0
                  align: TOP_MID
                  x: -50
                  y: 44
                  width: 150
                  height: 140
                  hidden: False
                  widgets:
                    - label:
                        align: TOP_MID
                        text_font: lato_24
                        text_color: color_white
                        text: "Tout éteindre"
                    - button:
                        #id: ${id_lvgl_widget_button}
                        width: 90
                        height: 90
                        y: 10
                        align: CENTER
                        bg_opa: TRANSP
                        shadow_opa: 100%
                        shadow_color: color_bright_white
                        shadow_spread: 4
                        shadow_width: 30
                        border_width: 2
                        radius: 50
                        on_press:
                          - homeassistant.action:
                              action: light.turn_off
                              data:
                                entity_id: light.toutes_les_lumieres_sauf_eclairage_exterieur
                        widgets:
                          - label:
                              align: CENTER
                              text_font: mdi_icons_72
                              text_color: color_bright_white
                              text: "${lights}"
