# Based of https://github.com/alaltitov/display/tree/main

# ESP32-S3-Touch-LCD-7
substitutions: !include hmi-garage/substitutions.yaml

packages:
  hardware: !include hmi-garage/hardware.yaml
  button: !include hmi-garage/components/button.yaml
  globals: !include hmi-garage/components/globals.yaml
  interval: !include hmi-garage/components/interval.yaml
  text_sensor: !include hmi-garage/components/text_sensor.yaml
  sensor: !include hmi-garage/components/sensor.yaml
  binary_sensor: !include hmi-garage/components/binary_sensor.yaml
  switch: !include hmi-garage/components/switch.yaml
  online_image: !include hmi-garage/components/online_image.yaml
  select: !include hmi-garage/components/select.yaml

  # LVGL
  page_home: !include hmi-garage/display/lvgl/page_home/page_home.yaml
  page_settings: !include hmi-garage/display/lvgl/sub_pages/page_settings.yaml
  page_music: !include hmi-garage/display/lvgl/sub_pages/page_music.yaml
  page_light_lampadaire_avant: !include hmi-garage/display/lvgl/sub_pages/page_light_lampadaire_avant.yaml
  page_light_garage_rdc: !include hmi-garage/display/lvgl/sub_pages/page_light_garage_rdc.yaml
  page_light_garage_ss: !include hmi-garage/display/lvgl/sub_pages/page_light_garage_ss.yaml
  page_light_exterieur_garage: !include hmi-garage/display/lvgl/sub_pages/page_light_exterieur_garage.yaml
  page_light_exterieur_cote: !include hmi-garage/display/lvgl/sub_pages/page_light_exterieur_cote.yaml
  
api:

http_request:
  verify_ssl: false

font: !include hmi-garage/display/fonts.yaml
image: !include hmi-garage/display/images.yaml
color: !include hmi-garage/display/colors.yaml

lvgl:
  gradients: !include hmi-garage/display/gradients.yaml  
  disp_bg_image: none
            
  top_layer: # Top Screen Status bar. Visible on all pages.
    widgets:
      - <<: !include hmi-garage/display/lvgl/top_layer/media_control_side_widget.yaml
      # Top notification area delimiter line
      - <<: !include hmi-garage/display/lvgl/top_layer/notification_area.yaml