sensor:
  # Weather temperature
  - platform: homeassistant
    id: weather_temp
    entity_id: weather.maison
    attribute: temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: id_lv_lab_weather_temperature
            text:
              format: "%.1f°C"
              args: x
              
  # Weather humidity
  - platform: homeassistant
    id: weather_hum
    entity_id: weather.maison
    attribute: humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: id_lv_lab_weather_humidity
            text:
              format: "%.0f%%"
              args: x
  # Weather wind speed
  - platform: homeassistant
    id: weather_precipitation
    entity_id: weather.maison
    attribute: wind_speed
    on_value: 
      then:
        - lvgl.label.update:
            id: id_lv_lab_weather_wind_speed
            text:
              format: "%.0fkm/h"
              args: x

  - platform: homeassistant
    id: gr_temp
    internal: True
    entity_id: sensor.yaris_remote_temperature
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_temperature_garage_rdc
            text:
              format: "%.1f°C"
              args: x
  - platform: homeassistant
    id: gr_hum
    internal: True
    entity_id: sensor.yaris_remote_humidty
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_humidity_garage_rdc
            text:
              format: "%.0f%%"
              args: x
  - platform: homeassistant
    id: gs_temp
    internal: True
    entity_id: sensor.acurite_tower_c_241_temperature
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_temperature_garage_ss
            text:
              format: "%.1f°C"
              args: x
  - platform: homeassistant
    id: gs_hum
    internal: True
    entity_id: sensor.acurite_tower_c_241_humidity
    on_value:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_humidity_garage_ss
            text:
              format: "%.0f%%"
              args: x

  - platform: homeassistant
    id: id_extc_bright
    internal: true
    entity_id: ${exterieur_cote_lights_ha_entity_id}
    attribute: brightness
    on_value:
      - if:
          condition:
            - lambda: 'return id(id_extc_bright).state > 0;' 
          then: 
            - lvgl.label.update:
                id: id_lv_lab_extc_bright_percent
                text:
                    format: "%.0f %%"
                    args: [id(id_extc_bright).state / 2.55]
            - lvgl.arc.update:
                id: id_lv_arc_extc_bright
                value: !lambda return x;
            - lvgl.button.update: 
                id: id_lv_but_page_extc
                shadow_spread: !lambda |-
                  uint8_t result = 2;
                  result += (uint8_t)(id(id_extc_bright).state / 255 * 20); // Swing from 3 to 21
                  return result;
                shadow_width: !lambda |-
                  uint8_t result = 20;
                  result += (uint8_t)(id(id_extc_bright).state / 2.55); // Swing from 21 to 120
                  return result;
    
  - platform: homeassistant
    id: id_extg_bright
    internal: true
    entity_id: ${exterieur_garage_lights_ha_entity_id}
    attribute: brightness
    on_value:
      - if:
          condition:
            - lambda: 'return id(id_extg_bright).state > 0;' 
          then: 
            - lvgl.label.update:
                id: id_lv_lab_extg_bright_percent
                text:
                    format: "%.0f %%"
                    args: [id(id_extg_bright).state / 2.55]
            - lvgl.arc.update:
                id: id_lv_arc_extg_bright
                value: !lambda return x;
            - lvgl.button.update: 
                id: id_lv_but_page_extg
                shadow_spread: !lambda |-
                  uint8_t result = 2;
                  result += (uint8_t)(id(id_extg_bright).state / 255 * 20); // Swing from 3 to 21
                  return result;
                shadow_width: !lambda |-
                  uint8_t result = 20;
                  result += (uint8_t)(id(id_extg_bright).state / 2.55); // Swing from 21 to 120
                  return result;
  
  # Light Lampadaire Avant Brightness
  - platform: homeassistant
    id: id_lamp_bright
    entity_id: ${lampadaire_avant_lights_ha_entity_id}
    internal: true
    attribute: brightness
    on_value:
      - if:
          condition:
            - lambda: 'return id(id_lamp_bright).state > 0;' 
          then: 
            - lvgl.label.update:
                id: id_lv_lab_lamp_percent
                text:
                    format: "%.0f %%"
                    args: [id(id_lamp_bright).state / 2.55]
            - lvgl.arc.update:
                id: id_lv_arc_lamp
                value: !lambda return x;
            - lvgl.button.update: 
                id: id_lv_but_page_lamp
                shadow_spread: !lambda |-
                  uint8_t result = 2;
                  result += (uint8_t)(id(id_lamp_bright).state / 255 * 20); // Swing from 3 to 21
                  return result;
                shadow_width: !lambda |-
                  uint8_t result = 20;
                  result += (uint8_t)(id(id_lamp_bright).state / 2.55); // Swing from 21 to 120
                  return result;

   # Light Extérieur Coté Kelvin
  - platform: homeassistant
    id: id_extc_kelvin
    entity_id: ${exterieur_cote_lights_ha_entity_id}
    internal: true
    attribute: color_temp_kelvin
    on_value:
      - globals.set:
          id: id_global_extc_kelvin
          value: !lambda |-
            if(std::isnan(x))
              return id(id_global_extc_kelvin);
            return static_cast<int>(x);
      - lvgl.slider.update:
          id: id_lv_slid_extc_kelvin
          value: !lambda return -x + (${exterieur_cote_min_kelvin} + ${exterieur_cote_max_kelvin});
      - lvgl.label.update:
          id: id_lv_lab_extc_kelvin
          text:
              format: "%.0f K"
              args: [id(id_extc_kelvin).state]

  # Light Extérieur Garage Kelvin
  - platform: homeassistant
    id: id_extg_kelvin
    entity_id: ${exterieur_garage_lights_ha_entity_id}
    internal: true
    attribute: color_temp_kelvin
    on_value:
      - globals.set:
          id: id_global_extg_kelvin
          value: !lambda |-
            if(std::isnan(x))
              return id(id_global_extg_kelvin);
            return static_cast<int>(x);
      - lvgl.slider.update:
          id: id_lv_slid_extg_kelvin
          value: !lambda return -x + (${exterieur_garage_min_kelvin} + ${exterieur_garage_max_kelvin});
      - lvgl.label.update:
          id: id_lv_lab_extg_kelvin
          text:
              format: "%.0f K"
              args: [id(id_extg_kelvin).state]


  # Light Lampadaire Avant Kelvin
  - platform: homeassistant
    id: id_lamp_kelvin
    entity_id: ${lampadaire_avant_lights_ha_entity_id}
    internal: true
    attribute: color_temp_kelvin
    on_value:
      - globals.set:
          id: id_global_lamp_kelvin
          value: !lambda |-
            if(std::isnan(x))
              return id(id_global_lamp_kelvin);
            return static_cast<int>(x);
      - lvgl.slider.update:
          id: id_lv_slid_lamp_kelvin
          value: !lambda return -x + (${lampadaire_avant_min_kelvin} + ${lampadaire_avant_max_kelvin});
      - lvgl.label.update:
          id: id_lv_lab_lamp_kelvin
          text:
              format: "%.0f K"
              args: [id(id_lamp_kelvin).state]

  # Media player volume value
  - platform: homeassistant
    id: id_media_volume
    entity_id: ${media_player_garage_entity_id}
    internal: true
    attribute: volume_level
    on_value:
      - lvgl.slider.update:
          id: id_lv_slid_media_volume
          value: !lambda "return x * 100.0;"